services:
  java-gateway:
    build:
      context: .
      dockerfile: ops/java/Dockerfile
    container_name: huginn-gateway
    ports:
      - "80:8080"
    volumes:
      - ./ui/web:/app/ui/web
    networks:
      - huginn-net
    depends_on:
      - laravel-front

  laravel-front:
    build:
      context: .
      dockerfile: ops/laravel/Dockerfile
    container_name: huginn-laravel-front
    ports:
      - "8081:8080"
    volumes:
      - ./apps/laravel-front:/var/www/html
    working_dir: /var/www/html
    command: sh -c "if [ -f artisan ]; then php artisan serve --host=0.0.0.0 --port=8080; else php -S 0.0.0.0:8080 -t public; fi"
    networks:
      - huginn-net
    depends_on:
          - symfony-back

  symfony-back:
    build:
      context: .
      dockerfile: ops/symfony/Dockerfile
    container_name: huginn-symfony-back
    ports:
      - "8082:8080"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - LLM_URL=http://llm:8008/generate/stream
      - LLM_METRICS_URL=http://llm:9108/metrics
    volumes:
      - ./apps/symfony-back:/app
    working_dir: /app
    #command: symfony serve --no-tls --port=8080 --dir=public
    networks:
      - huginn-net
    depends_on:
      - llm

  llm:
    build:
      context: .
      dockerfile: ops/python/Dockerfile
      target: app
    working_dir: /app
    command: ["python", "services/llm/supervisor.py"]
    volumes:
      - ./apps/python-llm:/app/apps/python-llm:rw
      - ./services/llm:/app/services/llm:rw
      - ./data:/data           # 👈 côté Windows ./data
      - ./ckpts:/ckpts
    environment:
      - PYTHONPATH=/app/apps/python-llm
      - CKPT_PATH=/ckpts/rnn.pt
      - METRICS_PORT=9108
      - PYTHONUNBUFFERED=1
    ports:
      - "9108:9108"   # /metrics
    networks:
      - huginn-net

volumes:
  llm_ckpts:
  llm_data:

networks:
  huginn-net:
    driver: bridge
