services:
  java-gateway:
    build:
      context: .
      dockerfile: ops/java/Dockerfile
    container_name: huginn-gateway
    ports:
      - "80:8080"
    volumes:
      - ./ui/web:/app/ui/web
    networks:
      - huginn-net
    depends_on:
      - php-gateway
  php-gateway:
    build:
      context: .
      dockerfile: ops/php/Dockerfile
    volumes:
      - ./apps/php/public:/app/public
    networks:
      - huginn-net


networks:
  huginn-net:
    driver: bridge